INSERT INTO PLANOS(TIPO)VALUES('Individual')
INSERT INTO PLANOS(TIPO)VALUES('Família')
INSERT INTO PLANOS(TIPO)VALUES('Max')



INSERT INTO DBO.FORMA_DE_PAGAMENTO(DESCRICAO)VALUES('Cartão de crédito')
INSERT INTO DBO.FORMA_DE_PAGAMENTO(DESCRICAO)VALUES('Boleto')
INSERT INTO DBO.FORMA_DE_PAGAMENTO(DESCRICAO) VALUES('PIX')
INSERT INTO DBO.FORMA_DE_PAGAMENTO(DESCRICAO) VALUES ('Carnê');
INSERT INTO DBO.FORMA_DE_PAGAMENTO(DESCRICAO) VALUES ('PicPay');
INSERT INTO DBO.FORMA_DE_PAGAMENTO(DESCRICAO) VALUES ('Google Pay');
INSERT INTO DBO.FORMA_DE_PAGAMENTO(DESCRICAO) VALUES ('Mercado Pago');




INSERT INTO DBO.CLIENTES(NOME,EMAIL,IDADE,SENHA,TELEFONE,ID_PLANO,ID_FORMA_DE_PAGAMENTO)
VALUES('Carlos Araújo','Carlos2022@hotmail.com',23,'12345678','83967899876',2,1)
INSERT INTO DBO.CLIENTES(NOME,EMAIL,IDADE,SENHA,TELEFONE,ID_PLANO,ID_FORMA_DE_PAGAMENTO)
VALUES('Alberto Alves','Albertinho112@hotmail.com',19,'12225678','83967789896',2,3)
INSERT INTO DBO.CLIENTES(NOME,EMAIL,IDADE,SENHA,TELEFONE,ID_PLANO,ID_FORMA_DE_PAGAMENTO)
VALUES('Roberto Carlos','Robertocarlos06@hotmail.com',55,'32145678','83342599876',1,2)
INSERT INTO DBO.CLIENTES(NOME,EMAIL,IDADE,SENHA,TELEFONE,ID_PLANO,ID_FORMA_DE_PAGAMENTO)
VALUES('Maria Clara','Mc2004@hotmail.com',21,'12345098','83967089876',3,1)
INSERT INTO DBO.CLIENTES(NOME,EMAIL,IDADE,SENHA,TELEFONE,ID_PLANO,ID_FORMA_DE_PAGAMENTO)
VALUES('Jordânia Alvarenga','jordaniaaaa12@hotmail.com',43,'27345678','83967887696',1,2)
INSERT INTO DBO.CLIENTES(NOME,EMAIL,IDADE,SENHA,TELEFONE,ID_PLANO,ID_FORMA_DE_PAGAMENTO)
VALUES('Levi de Souza Folly', 'levi.folly@geradornv.com.br',44,'85746352','83976850987',3,4)
INSERT INTO DBO.CLIENTES(NOME,EMAIL,IDADE,SENHA,TELEFONE,ID_PLANO,ID_FORMA_DE_PAGAMENTO)
VALUES('Everton Cormack Siqueira', 'everton.siqueira@geradornv.com.br',22,'85746352','83976850987',2,1)
INSERT INTO DBO.CLIENTES(NOME,EMAIL,IDADE,SENHA,TELEFONE,ID_PLANO,ID_FORMA_DE_PAGAMENTO)
VALUES('Alessandro Temperini Antunes', 'alessandro.antunes@geradornv.com.br',18,'85746352','83976850987',1,1)
INSERT INTO DBO.CLIENTES(NOME,EMAIL,IDADE,SENHA,TELEFONE,ID_PLANO,ID_FORMA_DE_PAGAMENTO)
VALUES('Jonathan Branco Zuniga', 'jonathan.zuniga@geradornv.com.br',34,'85746352','83976850987',2,2)
INSERT INTO DBO.CLIENTES(NOME,EMAIL,IDADE,SENHA,TELEFONE,ID_PLANO,ID_FORMA_DE_PAGAMENTO)
VALUES('Jonathan Branco Zuniga', 'jonathan.zuniga@geradornv.com.br',34,'85746352','83976850987',3,4)


INSERT INTO FILME VALUES('A Casa Monstro', '01:34:20',1)
INSERT INTO FILME VALUES('500 dias com ela', '01:35:00',1)
INSERT INTO FILME VALUES('Homem-Aranha 3', '02:37:05',0)
INSERT INTO FILME VALUES('Vingadores: Ultimato', '03:20:10',1)
INSERT INTO FILME VALUES('Um dia', '01:48:20',1)
INSERT INTO FILME VALUES('Whiplash', '01:46:00',1)
INSERT INTO FILME VALUES('Taxi Driver', '01:53:00',0)
INSERT INTO FILME VALUES('Clube da luta', '02:19:00',1)
INSERT INTO FILME VALUES('Batman vs Superman', '02:31:00',0)
INSERT INTO FILME VALUES('Spirit: Corcel Indomável', '01:24:00',1)

INSERT INTO SERIE VALUES('Greys Anatomy', 300,0)
INSERT INTO SERIE VALUES('Peaky Blinders', 50,0)
INSERT INTO SERIE VALUES('HOW I MET YOUR MOTHER', 80,1)
INSERT INTO SERIE VALUES('One Piece', 1000,1)
INSERT INTO SERIE VALUES('Brooklyn 99', 76,0)
INSERT INTO SERIE VALUES('Cobra Kai', 40,1)
INSERT INTO SERIE VALUES('Elite', 44 ,0)
INSERT INTO SERIE VALUES('Suits', 10,1)
INSERT INTO SERIE VALUES('The good doctor', 55,1)
INSERT INTO SERIE VALUES('Titans', 33,0)

INSERT INTO WATCHING(ID_FILME,ID_CLIENTE)VALUES(2,3)
INSERT INTO WATCHING(ID_FILME,ID_CLIENTE)VALUES(1,5)
INSERT INTO WATCHING(ID_FILME,ID_CLIENTE)VALUES(6,5)
INSERT INTO WATCHING(ID_FILME,ID_CLIENTE)VALUES(7,3)
INSERT INTO WATCHING(ID_FILME,ID_CLIENTE)VALUES(3,7)
INSERT INTO WATCHING(ID_FILME,ID_CLIENTE)VALUES(2,8)
INSERT INTO WATCHING(ID_SERIE,ID_CLIENTE)VALUES(5,6)
INSERT INTO WATCHING(ID_SERIE,ID_CLIENTE)VALUES(6,3)
INSERT INTO WATCHING(ID_SERIE,ID_CLIENTE)VALUES(2,6)
